Add zero_extendi and sign_extendi to intrinsic namespace
tensorflow/mlir pull request #333
Opened 2019-12-20 19:36 UTC by pruthviIntel

This PR add's zero_extendi and sign_extendi to intrinsic namespace

2019-12-23 12:50 UTC, ftynse requested changes

2019-12-23 12:50 UTC, ftynse commented on test/EDSC/builder-api-test.cpp
> +  AffineLoopNestBuilder({&i, &j}, {zero, zero}, {one, one}, {1, 1})([&]{
Could you make these tests more minimal? They end up testing the combination of AffineLoopNextBuilder, IndexedValue, accessor generator and the call you introduced. Building something like

```
func @f(%arg0: i1) -> i8 {
  %0 = sextend_i %arg0 : i1 to i8
  return %0 : i8
}
```

should be sufficient and would minimize the risk of this test being broken when irrelevant parts (affine loops, indexedValue) are changed.

2019-12-26 10:05 UTC, ftynse approved these changes

2020-01-08 18:07 UTC, pruthviIntel commented
ported this PR to LLVM monorepo, https://reviews.llvm.org/D72298. 
So closing this PR

2020-01-08 18:07 UTC, closed without merging