Add uitofp to the standard dialect.
tensorflow/mlir pull request #335
Opened 2019-12-22 22:50 UTC by ombre5733

The operation 'uitofp', which converts an unsigned integer to a floating-point
value was already part of the LLVM dialect. Contrary to its sibling 'sitofp' it
had no corresponding operation in the standard dialect.

This adds UIToFPOp to the standard dialect and a lowering to 'uitofp' in LLVM.
The work is mostly copy-paste of the existing SIToFPOp.

2020-01-06 05:06 UTC, River707 requested changes

2020-01-06 05:06 UTC, River707 commented on include/mlir/Dialect/StandardOps/Ops.td
> +  let hasFolder = 0;
Why is this set to 0?

2020-01-06 05:06 UTC, River707 commented on include/mlir/Dialect/StandardOps/Ops.td
> +def UIToFPOp : CastOp<"uitofp">, Arguments<(ins AnyType:$in)> {
We should constrain the input to be an integer type, and the output to a floating point.

2020-01-06 05:06 UTC, River707 commented on lib/Dialect/StandardOps/Ops.cpp
> +// uitofp is applicable from integer types to float types.
Use /// for function comments.

2020-01-06 05:06 UTC, River707 commented on lib/Dialect/StandardOps/Ops.cpp
> +//===----------------------------------------------------------------------===//
Keep the operations sorted to match .td file.

2020-03-10 08:42 UTC, ombre5733 commented
This PR was made back in the days when MLIR was not integrated into LLVM. Since submissions happen via Phabricator now, I'm closing this issue. I'll re-submit something once I have time to familiarize with Phabricator, arcanist and whatever more is needed.

2020-03-10 08:42 UTC, closed without merging